mysql -P 51524 -u gbrey -h curlew.cch.kcl.ac.uk -B -e 'SELECT DISTINCT tscomposerName FROM TSComposers ORDER BY tscomposerName' hofmeister >hofmeister.TSComposers.tscomposerName.txt
mysql -P 51524 -u gbrey -h curlew.cch.kcl.ac.uk -B -e 'SELECT DISTINCT tspublisherName FROM TSPublishers ORDER BY tspublisherName' hofmeister >hofmeister.TSPublishers.tspublisherName.txt
mysql -P 51524 -u gbrey -h curlew.cch.kcl.ac.uk -B -e 'SELECT DISTINCT tspubplaceName FROM TSPubPlaces ORDER BY tspubplaceName' hofmeister >hofmeister.TSPubPlaces.tspubplaceName.txt
mysql -P 51524 -u gbrey -h curlew.cch.kcl.ac.uk -B -e 'SELECT DISTINCT Element FROM Uniq_artist ORDER BY Element' hofmeister >hofmeister.Uniq_artist.Element.txt
mysql -P 51524 -u gbrey -h curlew.cch.kcl.ac.uk -B -e 'SELECT DISTINCT Element FROM Uniq_author ORDER BY Element' hofmeister >hofmeister.Uniq_author.Element.txt
mysql -P 51524 -u gbrey -h curlew.cch.kcl.ac.uk -B -e 'SELECT DISTINCT Element FROM Uniq_composer ORDER BY Element' hofmeister >hofmeister.Uniq_composer.Element.txt
mysql -P 51524 -u gbrey -h curlew.cch.kcl.ac.uk -B -e 'SELECT DISTINCT Element FROM Uniq_publisher ORDER BY Element' hofmeister >hofmeister.Uniq_publisher.Element.txt
mysql -P 51524 -u gbrey -h curlew.cch.kcl.ac.uk -B -e 'SELECT DISTINCT Element FROM Uniq_pubPlace ORDER BY Element' hofmeister >hofmeister.Uniq_pubPlace.Element.txt
mysql -P 51524 -u gbrey -h curlew.cch.kcl.ac.uk -B -e 'SELECT DISTINCT Element FROM Uniq_subject ORDER BY Element' hofmeister >hofmeister.Uniq_subject.Element.txt
mysql -P 51524 -u gbrey -h curlew.cch.kcl.ac.uk -B -e 'SELECT DISTINCT varcomposerName FROM VarComposers ORDER BY varcomposerName' hofmeister >hofmeister.VarComposers.varcomposerName.txt
mysql -P 51524 -u gbrey -h curlew.cch.kcl.ac.uk -B -e 'SELECT DISTINCT varpublisherName FROM VarPublishers ORDER BY varpublisherName' hofmeister >hofmeister.VarPublishers.varpublisherName.txt
mysql -P 51524 -u gbrey -h curlew.cch.kcl.ac.uk -B -e 'SELECT DISTINCT varpubplaceName FROM VarPubPlaces ORDER BY varpubplaceName' hofmeister >hofmeister.VarPubPlaces.varpubplaceName.txt
