# -*- python -*-
# Configuration file for prxml to tokenDB conversion
# Sets various variables
# for simplicity follows Python syntax

generatearttext = True

corpusinpath = "/Volumes/BYLACIE160/projects/cch/ncse/skua/Drive_E_OliveInternal/2007/TEC-20070703"

corpusimagebasedir = "/projects/cch/ncse/olive/corpusimg/TEC"
generatecorpusimages = False

# db_type = "SQLite"
db_type = "MySQL"
# 
# db_output = "DB"
db_output = "File"
# 
# DON'T FORGET TO ADAPT db_path and db_create_file !!!
# 
# db_path = "/mnt/ncse_svn/textmining/db/sql/sqlite"
db_path = "/projects/cch/ncse/textmining/db/sql/mysql"
# 
# db_create_file = "/projects/cch/ncse/textmining/db/sql/sqlite/ncse_tokens_create.sql"
db_create_file = "/projects/cch/ncse/textmining/db/sql/mysql/ncse_tokens_create.sql"
# 
db_name = "ncse_tokens"
db_host = "localhost"
db_port = "51524"
db_user = "gbrey"
db_passwd = "Ujs92ila"

