# -*- python -*-
# Configuration file for prxml to tokenDB conversion
# Sets various variables
# for simplicity follows Python syntax

generatearttext = True

corpusinpath = "/ncserepository/curr/CLD"

corpusimagebasedir = "/ncsecorpusimg/CLD"
generatecorpusimages = False

# db_type = "SQLite"
db_type = "MySQL"
# 
# db_outputdb_output = "DB"
db_output = "File"
# 
# DON'T FORGET TO ADAPT db_path and db_create_file !!!
# 
# db_path = "/mnt/ncse_svn/textmining/db/sql/sqlite"
db_path = "/projects/cch/ncse/textmining/db/sql/mysql"
# 
# location where TAB delimited tokens table should be written to
db_load_path = "/ncseloaddata"
#
db_mysql_data_path = "/usr/local/mysql/data"
#
# db_create_file = "/projects/cch/ncse/textmining/db/sql/sqlite/ncse_tokens_and_types_create.sql"
db_create_file = "/projects/cch/ncse/textmining/db/sql/mysql/ncsetoks_create_myisam.sql"
# 
db_name = "ncsetoks_cld"
db_host = "localhost"
db_port = "51524"
db_user = "gbrey"
db_passwd = "Ujs92ila"

