#!/bin/sh
currdatebefore=`date +%Y%m%d%H%M`
echo "Processing EWJ ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a EWJ -r "_"
echo "Processing LDR ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a LDR -r "_"
echo "Processing MRP ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a MRP -r "_"
echo "Processing NSS ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a NSS -r "_"
echo "Processing TEC ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a TEC -r "_"
echo "Processing TTW ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a TTW -r "_"
echo "Processing FEWJ .."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a FEWJ -r "_"
echo "Processing FLDR ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a FLDR -r "_"
echo "Processing CLD ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a CLD -r "_"
echo "Processing EMRP ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a EMRP -r "_"
echo "Processing FMRP ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a FMRP -r "_"
echo "Processing SMRP ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a SMRP -r "_"
echo "Processing SNSS ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a SNSS -r "_"
echo "Processing NS2 ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a NS2 -r "_"
echo "Processing NS3 ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a NS3 -r "_"
echo "Processing NS4 ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a NS4 -r "_"
echo "Processing NS5 ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a NS5 -r "_"
echo "Processing NS6 ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a NS6 -r "_"
echo "Processing NS7 ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a NS7 -r "_"
echo "Processing NS8 ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a NS8 -r "_"
echo "Processing NS9 ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a NS9 -r "_"
echo "Processing FTEC ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a FTEC -r "_"
echo "Processing TTEC ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a TTEC -r "_"
echo "Processing ATTW ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a ATTW -r "_"
echo "Processing ETTW ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a ETTW -r "_"
echo "Processing FTTW ..."
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a FTTW -r "_"
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a SCLD
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a SLDR
./ncseall-to-lucene.py -o /home/ncseoutput/lucene -l /home/ncseoutput/logs -a SXLDR
currdateafter=`date +%Y%m%d%H%M`
echo "START: $currdatebefore" >/home/ncseoutput/logs/ncseall-to-lucene-all-$currdateafter.log
echo "END  : $currdateafter" >>/home/ncseoutput/logs/ncseall-to-lucene-all-$currdateafter.log
