#!/bin/sh
currdatebefore=`date +%Y%m%d%H%M`
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a EWJ -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a LDR -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a MRP -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a NSS -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a TEC -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a TTW -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a FEWJ -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a FLDR -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a CLD -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a EMRP -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a FMRP -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a SMRP -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a SNSS -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a NS2 -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a NS3 -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a NS4 -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a NS5 -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a NS6 -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a NS7 -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a NS8 -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a NS9 -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a FTEC -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a TTEC -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a ATTW -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a ETTW -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a FTTW -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a SCLD -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a SLDR -c 300 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncsedata/lucene-similarity-input-w-texts-min300chars -l /home/ncsedata/lucene-similarity-input-w-texts-min300chars-log -a SXLDR -c 300 -r "_"
currdateafter=`date +%Y%m%d%H%M`
echo "START: $currdatebefore" >/home/ncseoutput/logs/ncseall-to-lucene-all-$currdateafter.log
echo "END  : $currdateafter" >>/home/ncseoutput/logs/ncseall-to-lucene-all-$currdateafter.log
