#!/bin/sh
currdatebefore=`date +%Y%m%d%H%M`
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a EWJ -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a LDR -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a MRP -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a NSS -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a TEC -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a TTW -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a FEWJ -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a FLDR -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a CLD -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a EMRP -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a FMRP -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a SMRP -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a SNSS -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a NS2 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a NS3 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a NS4 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a NS5 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a NS6 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a NS7 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a NS8 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a NS9 -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a FTEC -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a TTEC -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a ATTW -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a ETTW -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a FTTW -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a SCLD -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a SLDR -r "_"
./ncseall-to-lucene-plus-text-for-similarity.py -o /home/ncseoutput/lucene-similarity-input-w-texts -l /home/ncseoutput/lucene-similarity-input-w-texts-log -a SXLDR -r "_"
currdateafter=`date +%Y%m%d%H%M`
echo "START: $currdatebefore" >/home/ncseoutput/logs/ncseall-to-lucene-all-$currdateafter.log
echo "END  : $currdateafter" >>/home/ncseoutput/logs/ncseall-to-lucene-all-$currdateafter.log
