# metadata field definitions for prxml-extract-metadata.py

# key to prefixes:
# prefixes consist of 3 parts, delimited by underscores
# 
# part 1:
# c_: generated by GB at CCH
# o_: generated by Olive system
# n_: generated my manual entry by NCSE team
# 
# part 2:
# toc_: information derived from TOC.xml file
# ent_: information derived from various entity/article XML files
# 
# part 3:
# meta_: information derived from attributes in first "meta" element
# enty_: information derived from attributes in entity element
# appd_: information derived from sub-elements and attributes of
#        Application_Data / Application_Info elements
# sect_: information derived from attributes in section element
# page_: information derived from attributes in page element
# 

c_toc_meta = "c_toc_meta"
c_toc_enty = "c_toc_enty"
o_toc_meta = "o_toc_meta"
o_ent_appd = "o_ent_appd"
n_ent_appd = "n_ent_appd"
o_toc_appd = "o_toc_appd"
n_toc_appd = "n_toc_appd"
o_ent_meta = "o_ent_meta"
o_toc_sect = "o_toc_sect"
o_toc_page = "o_toc_page"
o_toc_enty = "o_toc_enty"

mdfieldlistseq1 = [
                   c_toc_meta,
                   c_toc_enty,
                   o_toc_meta,
                   o_ent_appd,
                   n_ent_appd,
                   o_toc_appd,
                   n_toc_appd,
                   o_ent_meta,
                   o_toc_sect,
                   o_toc_page,
                   o_toc_enty
                   ]

mdfieldlistseq2 = [
                   c_toc_meta,
                   c_toc_enty,
                   o_toc_meta,
                   o_toc_appd,
                   n_toc_appd,
                   o_toc_sect,
                   o_toc_page,
                   o_toc_enty,
                   o_ent_meta,
                   o_ent_appd,
                   n_ent_appd
                   ]

mdfieldlistdic = {}
mdfieldlistsqldic = {}

mdfieldlistdic[c_toc_meta] = [
    "c_toc_meta_fullartid",
    "c_toc_meta_publname"
    ]

mdfieldlistdic[c_toc_enty] = [
    "c_toc_enty_articleid",
    "c_toc_enty_entityid",
    "c_toc_enty_siblingids",
    ]

mdfieldlistdic[o_toc_meta] = [
#    "o_toc_meta_publisher",
    "o_toc_meta_pages_number",
#    "o_toc_meta_source_type",
#    "o_toc_meta_source_resolution",
#    "o_toc_meta_images_resolution",
#    "o_toc_meta_page_thumbnail_resolution",
#    "o_toc_meta_page_preview_resolution",
#    "o_toc_meta_profile_id",
    "o_toc_meta_base_href",
#    "o_toc_meta_default_img_ext",
#    "o_toc_meta_default_preview_img_ext",
    "o_toc_meta_issue_day",
    "o_toc_meta_issue_month",
    "o_toc_meta_issue_year",
#    "o_toc_meta_pdf_destination_mapped",
#    "o_toc_meta_ad_snp_ext",
#    "o_toc_meta_title_snp_ext",
#    "o_toc_meta_image_snp_ext",
    "o_toc_meta_multi_layer_page_img",
    "o_toc_meta_is_solid",
    ]

mdfieldlistdic[o_ent_appd] = [
    "o_ent_appd_ep_path",
    ]

mdfieldlistdic[n_ent_appd] = [
    "n_ent_appd_kc_periodicaltitle",
    "n_ent_appd_kc_actualtitle",
    "n_ent_appd_kc_volume",
    "n_ent_appd_kc_number",
    "n_ent_appd_kc_edition",
    "n_ent_appd_kc_imgdesc",
    "n_ent_appd_kc_price",
    "n_ent_appd_kc_bibliographic",
    "n_ent_appd_kc_departmentgeneric",
    "n_ent_appd_kc_pagespanitem",
    "n_ent_appd_kc_departmenttitle",
    "n_ent_appd_kc_numofedition",
    "n_ent_appd_kc_editor",
    "n_ent_appd_dc_title",
    "n_ent_appd_dc_date",
    "n_ent_appd_dc_source",
    "n_ent_appd_dc_description",
    "n_ent_appd_dc_format",
    "n_ent_appd_dc_subject",
    "n_ent_appd_dc_creator",
    "n_ent_appd_dc_publisher",
    "n_ent_appd_dc_contributor",
    "n_ent_appd_dc_identifier",
    "n_ent_appd_dc_language",
    "n_ent_appd_dc_coverage",
    "n_ent_appd_dc_type",
    "n_ent_appd_dc_relation",
    "n_ent_appd_dc_rights",
    ]

mdfieldlistdic[o_toc_appd] = [
    "o_toc_appd_ep_path",
    ]

mdfieldlistdic[n_toc_appd] = [
    "n_toc_appd_kc_periodicaltitle",
    "n_toc_appd_kc_actualtitle",
    "n_toc_appd_kc_volume",
    "n_toc_appd_kc_number",
    "n_toc_appd_kc_edition",
    "n_toc_appd_kc_imgdesc",
    "n_toc_appd_kc_price",
    "n_toc_appd_kc_bibliographic",
    "n_toc_appd_kc_departmentgeneric",
    "n_toc_appd_kc_pagespanitem",
    "n_toc_appd_kc_departmenttitle",
    "n_toc_appd_kc_numofedition",
    "n_toc_appd_kc_editor",
    "n_toc_appd_dc_title",
    "n_toc_appd_dc_date",
    "n_toc_appd_dc_source",
    "n_toc_appd_dc_description",
    "n_toc_appd_dc_format",
    "n_toc_appd_dc_subject",
    "n_toc_appd_dc_creator",
    "n_toc_appd_dc_publisher",
    "n_toc_appd_dc_contributor",
    "n_toc_appd_dc_identifier",
    "n_toc_appd_dc_language",
    "n_toc_appd_dc_coverage",
    "n_toc_appd_dc_type",
    "n_toc_appd_dc_relation",
    "n_toc_appd_dc_rights",
    ]

mdfieldlistdic[o_ent_meta] = [
#    "o_ent_meta_name",
    "o_ent_meta_base_href",
#    "o_ent_meta_source_type",
    "o_ent_meta_publication",
    "o_ent_meta_section",
    "o_ent_meta_wordcnt",
#    "o_ent_meta_images_resolution",
    "o_ent_meta_issue_date",
    "o_ent_meta_issue_day",
    "o_ent_meta_issue_month",
    "o_ent_meta_issue_year",
    "o_ent_meta_release_no",
    "o_ent_meta_page_id",
    "o_ent_meta_page_type",
    "o_ent_meta_page_width",
    "o_ent_meta_page_height",
#    "o_ent_meta_default_img_ext",
    "o_ent_meta_description",
    "o_ent_meta_subtype",
#    "o_ent_meta_pdf_destination_mapped",
    "o_ent_meta_embedded_into",
    "o_ent_meta_page_label",
    "o_ent_meta_embedded_after",
    ]

mdfieldlistdic[o_toc_sect] = [
    "o_toc_sect_section_name",
    ]

mdfieldlistdic[o_toc_page] = [
    "o_toc_page_single_page_pdf_name",
    "o_toc_page_page_no",
    "o_toc_page_page_ID",
    "o_toc_page_page_label",
    "o_toc_page_id",
    "o_toc_page_name",
    "o_toc_page_href",
    "o_toc_page_page_type",
    "o_toc_page_page_width",
    "o_toc_page_page_height",
#    "o_toc_page_img_ext",
#    "o_toc_page_preview_img_ext",
#    "o_toc_page_working_status",
    "o_toc_page_crop_box",
    "o_toc_page_media_box",
    "o_toc_page_ext_page_type",
    ]

mdfieldlistdic[o_toc_enty] = [
    "o_toc_enty_entity_type",
    "o_toc_enty_rendering_opt",
#    "o_toc_enty_name",
    "o_toc_enty_logical_name",
    "o_toc_enty_id",
    "o_toc_enty_href",
    "o_toc_enty_no_geometry",
    "o_toc_enty_page_no",
    "o_toc_enty_size",
    "o_toc_enty_continuation_to",
    "o_toc_enty_continuation_from",
    "o_toc_enty_embedded_into",
    "o_toc_enty_entity_format",
#    "o_toc_enty_working_status",
#    "o_toc_enty_expired_time",
#    "o_toc_enty_snp",
    "o_toc_enty_is_general",
    "o_toc_enty_embedded_after",
    "o_toc_enty_exclude_from_search",
#    "o_toc_enty_images_resolution",
    "o_toc_enty_first_toc_entry_id",
    "o_toc_enty_depth_level",
    "o_toc_enty_index_in_doc",
    ]

mdfieldlistsqldic[o_toc_enty] = [
    [ "o_toc_enty_entity_type" , "v" ],
    [ "o_toc_enty_rendering_opt" , "v" ],
    [ "o_toc_enty_name" , "v" ],
    [ "o_toc_enty_logical_name" , "v" ],
    [ "o_toc_enty_id" , "v" ],
    [ "o_toc_enty_href" , "v" ],
    [ "o_toc_enty_no_geometry" , "v" ],
    [ "o_toc_enty_page_no" , "i" ],
    [ "o_toc_enty_size" , "v" ],
    [ "o_toc_enty_continuation_to" , "v" ],
    [ "o_toc_enty_continuation_from" , "v" ],
    [ "o_toc_enty_embedded_into" , "v" ],
    [ "o_toc_enty_entity_format" , "v" ],
    [ "o_toc_enty_working_status" , "v" ],
    [ "o_toc_enty_expired_time" , "v" ],
    [ "o_toc_enty_snp" , "v" ],
    [ "o_toc_enty_is_general" , "v" ],
    [ "o_toc_enty_embedded_after" , "v" ],
    [ "o_toc_enty_exclude_from_search" , "v" ],
    [ "o_toc_enty_images_resolution" , "i" ],
    [ "o_toc_enty_first_toc_entry_id" , "i" ],
    [ "o_toc_enty_depth_level" , "i" ],
    [ "o_toc_enty_index_in_doc" , "i" ],
    ]

textfields = [
#              "o_toc_enty_name",
#              "o_ent_meta_name",
              "c_toc_enty_siblingids",
              "n_toc_appd_kc_imgdesc",
              "n_ent_appd_kc_imgdesc",
              ]

indexfields = [
               "c_toc_meta_fullartid",
               "c_toc_enty_articleid",
               "c_toc_enty_entityid",
               "o_ent_meta_embedded_into",
               "o_ent_meta_embedded_after",
               ]

fullartidfieldslist = [
                       "c_toc_meta_publname",
                       "n_ent_appd_kc_periodicaltitle",
                       "n_ent_appd_kc_actualtitle",
                       "n_ent_appd_kc_volume",
                       "n_ent_appd_kc_number",
                       "n_ent_appd_kc_edition",
                       "n_toc_appd_kc_periodicaltitle",
                       "n_toc_appd_kc_actualtitle",
                       "n_toc_appd_kc_volume",
                       "n_toc_appd_kc_number",
                       "n_toc_appd_kc_edition",
                       ]

listformatfields = [
                    "n_toc_appd_kc_imgdesc",
                    "n_ent_appd_kc_imgdesc",
                    ]

mdfieldlist1 = []
for e in mdfieldlistseq1:
    for f in mdfieldlistdic[e]:
        mdfieldlist1.append(f)

# list ordered by source (toc, ent)        
mdfieldlist2 = []
for e in mdfieldlistseq2:
    for f in mdfieldlistdic[e]:
        mdfieldlist2.append(f)

# list ordered by "suffix", i. e. actual field name
mdfieldlist3 = []
tmplist = mdfieldlist2
uniqsuffixlist = []
for s in mdfieldlist2:
    suff = s[11:]
    if suff not in uniqsuffixlist:
        uniqsuffixlist.append(suff)
for s in uniqsuffixlist:
    for m in mdfieldlist2:
        suff = m[11:]
        if s == suff:
            mdfieldlist3.append(m)



# SUFFIXES:
# "o_" - metadata provided by Olive
# "n_" - metadata provided by NCSE team
# "c_" - metadata provided by this program

#allentitymetadatalist = [
#                  [ "o_publname", "'" ],
#                  [ "c_fullartid", "'" ],
#                  [ "c_articleid", "'" ],
#                  [ "c_siblingids", "'" ],
#                  [ "c_entityid", "'" ],
#                  [ "o_ep_path", "'" ],
#                  [ "o_section_name", "'" ],
#                  [ "o_page_no", "" ],
#                  [ "o_page_label", "'" ],
#                  [ "o_entity_type", "'" ],
#                  [ "o_entity_subtype", "'" ],
#                  [ "o_first_toc_entry_id", "" ],
#                  [ "o_depth_level", "" ],
#                  [ "o_index_in_doc", "" ],
#                  [ "o_logical_name", "'" ],
#                  [ "o_name", "'" ],
#                  [ "o_id", "'" ],
#                  [ "o_href", "'" ],
#                  [ "o_size", "'" ],
#                  [ "o_embedded_into", "'" ],
#                  [ "o_images_resolution", "" ],
#                  [ "o_continuation_from", "'" ],
#                  [ "o_continuation_to", "'" ],
#                  [ "o_wordcnt", "" ],
#                  [ "n_dc_title", "'" ],
#                  [ "n_kc_periodicalTitle", "'" ],
#                  [ "n_kc_actualTitle", "'" ],
#                  [ "n_dc_date", "'" ],
#                  [ "n_dc_source", "'" ],
#                  [ "n_kc_volume", "'" ],
#                  [ "n_kc_number", "'" ],
#                  [ "n_kc_edition", "'" ],
#                  [ "n_kc_NumOfEdition", "'" ],
#                  [ "n_kc_imgDesc", "'" ],
#                  [ "n_kc_price", "'" ],
#                  [ "n_kc_bibliographic", "'" ],
#                  [ "n_kc_departmentGeneric", "'" ],
#                  [ "n_dc_publisher", "'" ],
#                  [ "n_kc_editor", "'" ],
#                  [ "n_kc_departmentTitle", "'" ],
#                  [ "n_dc_description", "'" ],
#                  [ "n_dc_format", "'" ],
#                  [ "n_dc_subject", "'" ]
#                  ]

# allentitymetadatalist = bymetadatalist + pageentattlist + artmetadatalist





