#!/usr/bin/env python
# -*- coding: utf-8 -*-

# FMRP-1822-12-02: free standing image
# TTW-1867-06-01: free standing image on p. 43 (olive page no. 5)
# TEC-1889-12-16 p. 20: image embedded within article
# NSS-1837-12-16 p. 2: image embedded within article

# TODO: change the way image metadata are read
#       to account for cases like TEC-1889-12-16 p. 1
#          image metadata in Ar00100.xml (image in title page)
#          but no embedding information, i. e. no corresponding
#          Pc file exists
#          

import sys
import string

import os, os.path

from prxml_extract_metadata_fields import *

yewoutdir = "/projects/cch/ncse/textmining/db/sql/mysql"
ncsoutdir = "/home/ncsedata/ncse_svn/textmining/db/sql/mysql"
outfile = "ncsemetadata_create.sql"
yewoutfilepath = os.path.join(yewoutdir, outfile)
ncsoutfilepath = os.path.join(ncsoutdir, outfile)

if os.path.isdir(yewoutdir):
    outfileobj = file(yewoutfilepath, "w")
elif os.path.isdir(ncsoutdir):
    outfileobj = file(ncsoutfilepath, "w")
else:
    print
    print "STOPPED - NOT on yew or ncse-text!"
    print
    sys.exit()

header = """-- MySQL
-- 
-- automatically generated by prxml-extract-metadata-create-sql.py
-- 
-- fullartids, allmetadata
-- 
"""

faidsql = """
-- fullartids
-- full globally unique article id
CREATE TABLE `fullartids` (
  id integer unsigned NOT NULL auto_increment,
  fullartid varchar(254) CHARACTER SET latin1 COLLATE latin1_german1_ci,
  publ varchar(4),
  year integer unsigned,
  month integer unsigned,
  day integer unsigned,
  artid varchar(15),
  c_toc_meta_publname varchar(254),
  n_ent_appd_kc_periodicaltitle varchar(254),
  n_ent_appd_kc_actualtitle varchar(254),
  n_ent_appd_kc_volume varchar(254),
  n_ent_appd_kc_number varchar(254),
  n_ent_appd_kc_edition varchar(254),
  n_toc_appd_kc_periodicaltitle varchar(254),
  n_toc_appd_kc_actualtitle varchar(254),
  n_toc_appd_kc_volume varchar(254),
  n_toc_appd_kc_number varchar(254),
  n_toc_appd_kc_edition varchar(254),
  PRIMARY KEY (id),
  INDEX (fullartid),
  INDEX (publ),
  INDEX (year),
  INDEX (month),
  INDEX (day),
  INDEX (artid)
) ENGINE=MyISAM;
"""

allmetadataheader = """
-- allmetadata
CREATE TABLE `allmetadata` (
  id integer unsigned NOT NULL auto_increment,"""

allmetadataindexfooter = """  PRIMARY KEY (id),"""

allmetadatafooter = """) ENGINE=MyISAM;
"""

print >> outfileobj, header
print >> outfileobj, "DROP TABLE IF EXISTS `fullartids`;"
print >> outfileobj, "DROP TABLE IF EXISTS `allmetadata`;"
print >> outfileobj, ""
print >> outfileobj, faidsql
print >> outfileobj, ""
print >> outfileobj, ""
print >> outfileobj, allmetadataheader

for f in mdfieldlist3:
    if f in textfields:
        t = "text"
    else:
        t = "varchar(254)"
    sql = "  %s %s," % (f, t)
    print >> outfileobj, sql
print >> outfileobj, allmetadataindexfooter

indexfieldslen = len(indexfields)
for (n, f) in enumerate(indexfields):
    if n != indexfieldslen - 1:
        comma = ","
    else:
        comma = ""
    sql = "  INDEX (%s)%s" % (f, comma)
    print >> outfileobj, sql
print >> outfileobj, allmetadatafooter

outfileobj.close()

print "--== FINISHED ==--"
