#!/bin/sh
currdatebefore=`date +%Y%m%d%H%M`
python ./tokendb-to-corpus.py -d ncsetoks_ewj -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a EWJ -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ldr -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a LDR -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_mrp -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a MRP -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_nss -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a NSS -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_tec -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a TEC -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ttw -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a TTW -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_fewj -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a FEWJ -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_fldr -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a FLDR -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_cld -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a CLD -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_emrp -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a EMRP -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_fmrp -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a FMRP -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_smrp -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a SMRP -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_snss -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a SNSS -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ns2 -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a NS2 -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ns3 -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a NS3 -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ns4 -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a NS4 -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ns5 -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a NS5 -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ns6 -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a NS6 -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ns7 -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a NS7 -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ns8 -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a NS8 -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ns9 -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a NS9 -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ftec -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a FTEC -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ttec -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a TTEC -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_attw -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a ATTW -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_ettw -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a ETTW -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_fttw -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a FTTW -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_scld -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a SCLD -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_sldr -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a SLDR -f TXT -l month -c 300 -r "_"
python ./tokendb-to-corpus.py -d ncsetoks_sxldr -u gbrey -p Enah2un6 -o /home/ncsedata/corpustxt-20090224 -a SXLDR -f TXT -l month -c 300 -r "_"
currdateafter=`date +%Y%m%d%H%M` -r "_"
echo "START: $currdatebefore" >/home/ncsedata/corpustxt-20090224/tokendb-to-semtag-$currdateafter.log
echo "END  : $currdateafter" >>/home/ncsedata/corpustxt-20090224/tokendb-to-semtag-$currdateafter.log
