#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import string

import re
import socket
import platform
import time
import types
import os, os.path
from byutil import *
from bymysqlmap import *
# from xml.etree import ElementTree as ET
# from lxml import etree as ET
from optparse import OptionParser

outbasedir = "/projects/cch/ncse/waterloo/gategazetteers"
outpre = "waterloo_"
outmixext = "_mix.lst"
outcapext = "_cap.lst"
outlowext = "_low.lst"

rexmlent = re.compile(r"""&[^ ].*?;""")
#reetc = re.compile(r"""(&c.)""")
reetc = re.compile(r"""&(c|C)""")
reltgt = re.compile(r"""(<.*?>)""")
# reskwsatend = re.compile(r""",\s\w;$""")
reskwsatend = re.compile(r""",\s*(\w*?)\s*;\s*$""")
rekommawordatend = re.compile(r""",\s*(\w*?)\s*$""")
renameabbr = re.compile(r"""[A-Za-z]\.""")
resic = re.compile(r"""\[[Ss][Ii][Cc]\]""")
remultspace = re.compile(r"""  *""")

realentlist = (
               ("amp", "&"),
               ("apos", "'"),
               ("quot", '"'),
               ("lt", '<'),
               ("gt", '>')
               )

# generated by CheckForSemiColonAtEnd
# this was just produced for checking, as these are
# expressions that follow the pattern ", XXX;$"
kommaskgenreportlist = [
    "Cheriton",
    "Middlesex",
    "Oxfordshire",
    "Directory",
    "Midwifery",
    "Ireland",
    "Truro",
    "Hants",
    "Leeds",
    "London",
    "Worthing",
    "Calcutta",
    "Bolton",
    "Cornets",
    "England",
    "Radley",
    "Birmingham",
    "Illustrated",
    "Sunderland",
    "Manchester"
]

# etc

# generated by CheckForSemiColonAtEnd
# these (mostly articles) have to go to the beginning of the field
# in all other cases the semicolon at the end can simply be removed
kommaskbringtofrontlist = [
    "A",
    "An",
    "Der",
    "Die",
    "El",
    "Il",
    "La",
    "Le",
    "Les",
    "Lo",
    "O",
    "The",
    "Y",
    "Ye",
    "Yr"
    ]

kommagenreportlist = [
    "Aux",
    "Aintab",
    "Co",
    "DD",
    "Dos",
    "Inc",
    "Mother",
    "P",
    "Peter",
    "William",
    "arranger",
    "colonial",
    "jour",
    "journal",
    "late",
    "of",
    "proc",
    "rep",
    "tract",
    "trans",
    "transactions",
    "x"
]

kommabringtofrontlist = [
    "A",
    "An",
    "Aux",
    "Das",
    "De",
    "Den",
    "Der",
    "Di",
    "Die",
    "Dos",
    "El",
    "La",
    "Le",
    "Les",
    "Los",
    "Messeirs",
    "Messrs",
    "St",
    "Te",
    "The",
    "Y",
    "Ye",
    "Yr",
    "the",
    "un"
    ]


def printUsage():
    print
    print "ATTENTION:"
    print
    print "      ", os.path.basename(sys.argv[0]), "- you have to at least supply options '-o', '-d', '-a' , '-t' and '-l'"
    print
    print "      ", "get help with:"
    print "      ", os.path.basename(sys.argv[0]), "-h"
    print
    sys.exit(2)

def setupMySQL(dbhost, dbuser, dbpasswd, dbport, dbname):
    # for the time being we don't do any checking and just assume
    # that dbhost, etc. exist
    # dbhost = o.dbhost
    # dbname = o.dbname
    # dbport = o.dbport
    # dbuser = o.dbuser
    # dbpasswd = o.dbpass
    prog_host = socket.gethostname()
    # Ugly hack to make MySQLDb work on Linux and Windows
    # The LINUX version doesn't recognise the "charset" attribute
    # Look into it more closely:
    # - are the MySQLDb versions slightly different?
    # - do the different platform versions handle UNICODE differently?
    if prog_host.startswith("fir") == True:
        # by_use_unicode = True
        by_use_unicode = False
        by_charset = "latin1"
    elif prog_host.startswith("owl") == True:
        by_use_unicode = False
        # by_charset = "utf8"
        by_charset = "latin1"
    elif prog_host.startswith("box") == True:
        by_use_unicode = False
        # by_charset = "utf8"
        by_charset = "latin1"
    elif prog_host.startswith("numb") == True:
        # by_use_unicode = True
        by_use_unicode = False
        by_charset = "latin1"
    else:
        # changed: BY 08.02.12
        # by_use_unicode = True
        # by_charset = "latin1"
        by_use_unicode = False
        by_charset = "latin1"
    # print by_use_unicode
    # print by_charset
    # print dbhost
    # print dbname
    # sys.exit()
    if prog_host.startswith("owl") == True:
        # MySQL on OWL doesn't accept charset attribute
        mycon        = MySQLdb.connect(
                                       host=dbhost,
                                       port=dbport,
                                       user=dbuser,
                                       passwd=dbpasswd,
                                       db=dbname
                                       )
    else:
        # mycon        = MySQLdb.connect(
        #                                use_unicode=by_use_unicode,
        #                                charset=by_charset,
        #                                host=dbhost,
        #                                port=dbport,
        #                                user=dbuser,
        #                                passwd=dbpasswd,
        #                                db=dbname
        #                                )
        # changed: BY 08.02.12
        # TODO: work out how "use_unicode" and "charset" are really
        #       handled by the MySQLDB driver
        mycon        = MySQLdb.connect(
                                       host=dbhost,
                                       port=dbport,
                                       user=dbuser,
                                       passwd=dbpasswd,
                                       db=dbname
                                       )
    # Do _not_ create new DB structure, as we don't want to
    # delete data inserted in a previous run
    # createStrucMySQL(mycon, varsdic)
    # initFieldNames(mycon)
    return mycon

def getSqlQuery(sql, con):
    selobj = SqlResultList(con=con, sql=sql)
    rl = selobj.getRowTuple()
    rc = selobj.getRowCount()
    del selobj
    reslist = [r[0] for r in rl]
    return rc, rl


# replace expressions like "XXX, The;" with "The XXX"
# remove all trailing semi-colons
def ProcessSemiColonAtEnd(t):
    t = t.strip()
    if t.endswith(";"):
        skmo = re.search(reskwsatend, t)
        if skmo:
            skword = skmo.group(1)
            if skword in kommaskbringtofrontlist:
                t = re.sub(reskwsatend, "", t)
                t = skword + " " + t
                # print t
            else:
                t = t.rstrip(";")
        else:
            t = t.rstrip(";")
    return t


# normalise all "&c" to "etc"
def ProcessEtc(t):
    etc = re.search(reetc, t)
    if etc:
        t = re.sub(reetc, "etc", t)
    t = t.replace("etc.", "etc")
    return t

# normalise all "&" to "and"
def ProcessAmpersand(t):
    tf = t.find("&")
    if tf != -1:
        t = t.replace("&", " and ")
    return t

def ProcessSquareBrackets(t):
    if (t.find("[") > -1) or (t.find("]") > -1): 
        # print "-" * 50
        # print t
        # filter out year ranges preceded by "for ..."
        t = re.sub(r"""(for )+\[([0-9]{4} *-+ *[0-9]{4})\]""", r"""\1\2""", t)
        t = re.sub(r"""(for )+\[([0-9]{4} *to *[0-9]{4})\]""", r"""\1\2""", t)
        t = re.sub(r"""(for )+\[([0-9]{4})\]""", r"""\1\2""", t)
        t = re.sub(r"""(for the year )+\[([0-9]{4})\]""", r"""\1\2""", t)
        t = re.sub(r"""(for the Year )+\[([0-9]{4})\]""", r"""\1\2""", t)
        # print t
    # filter out "sic"
    if re.search(resic, t) != None:
        t = re.sub(resic, "", t)
    return t 

def ProcessFiltersMisc(t):
    # normalise multiple space to one space
    t = re.sub(remultspace, " ", t)
    return t
    
    
# remove all markup enclosed in "<" and ">"
def ProcessLtGt(t):
    ltgt = re.search(reltgt, t)
    if ltgt:
        t = re.sub(reltgt, "", t)
    return t


# replace expressions like "XXX, The" with "The XXX"
def ProcessEndWordsBringToFront(t):
    t = t.strip()
    kwe = re.search(rekommawordatend, t)
    if kwe:
        kword = kwe.group(1)
        if kword in kommabringtofrontlist:
            t = re.sub(rekommawordatend, "", t)
            t = kword + " " + t
            # print t
    return t

def processWlentries():
    sql = "SELECT id, category FROM categories WHERE id != 1"
    (rc, rt) = getSqlQuery(sql, con)
    for (catid, catname) in rt:
        sql = "SELECT wlentry FROM wlentries WHERE categoryid = %d" % (catid, )
        (rc, rt) = getSqlQuery(sql, con)
        if rc > 0:
            print catid, catname, rc
            tmplist = []
            for r in rt:
                entry = r[0]
                entry = entry.strip('?" ')
                # entry = entry.strip(' ')
                if (entry != '') and (entry not in tmplist):
                    tmplist.append(entry)
                    for ko in kommabringtofrontlist:
                        kolen = len(ko)
                        if entry.startswith("%s " % (ko, )):
                            # print "ko", entry
                            # entry = entry[kolen+1:]
                            tmplist.append(entry[kolen+1:])
            tmplist.sort()
            outfilemixname = outpre + catname + outmixext
            outfilecapname = outpre + catname + outcapext
            outfilelowname = outpre + catname + outlowext
            outfilemixpath = os.path.join(outbasedir, outfilemixname)
            outfilecappath = os.path.join(outbasedir, outfilecapname)
            outfilelowpath = os.path.join(outbasedir, outfilelowname)
            outfilemixobj = file(outfilemixpath, "w")
            outfilecapobj = file(outfilecappath, "w")
            outfilelowobj = file(outfilelowpath, "w")
            for en in tmplist:
                print >> outfilemixobj, en
                print >> outfilecapobj, en.upper()
                print >> outfilelowobj, en.lower()
            outfilemixobj.close()
            outfilecapobj.close()
            outfilelowobj.close()

def processTitleTable():
    sql = "SELECT title FROM title WHERE title != ''"
    (rc, rt) = getSqlQuery(sql, con)
    tmplist = []
    for r in rt:
        title = r[0]
        # print title
        title = ProcessLtGt(title)
        title = ProcessSemiColonAtEnd(title)
        title = ProcessEndWordsBringToFront(title)
        title = ProcessEtc(title)
        title = ProcessAmpersand(title)
        title = ProcessSquareBrackets(title)
        title = ProcessFiltersMisc(title)
        # print title
        title = title.strip('?" ')
        # title = title.strip(' ')
        if (title != '') and (title not in tmplist):
            tmplist.append(title)
            for ko in kommabringtofrontlist:
                kolen = len(ko)
                if title.startswith("%s " % (ko, )):
                    # eliminate entries that consist of numbers only
                    #   !!! not needed - only one occurance
                    # nothetitle = title[kolen+1:]
                    # if re.search(r"""^[0-9]+$""", nothetitle) != None:
                    #     print "NUM", title, nothetitle
                    #     # sys.exit()
                    #     t = ""
                    # print "ko", title
                    # title = title[kolen+1:]
                    tmplist.append(title[kolen+1:])
    tmplist.sort()
    outfilemixname = outpre + "title" + outmixext
    outfilecapname = outpre + "title" + outcapext
    outfilelowname = outpre + "title" + outlowext
    outfilemixpath = os.path.join(outbasedir, outfilemixname)
    outfilecappath = os.path.join(outbasedir, outfilecapname)
    outfilelowpath = os.path.join(outbasedir, outfilelowname)
    outfilemixobj = file(outfilemixpath, "w")
    outfilecapobj = file(outfilecappath, "w")
    outfilelowobj = file(outfilelowpath, "w")
    for en in tmplist:
        print >> outfilemixobj, en
        print >> outfilecapobj, en.upper()
        print >> outfilelowobj, en.lower()
    outfilemixobj.close()
    outfilecapobj.close()
    outfilelowobj.close()
                
def processFirstnameColumn():
    sql = "SELECT DISTINCT GivenName FROM peoplenames WHERE GivenName != '' ORDER BY GivenName"
    (rc, rt) = getSqlQuery(sql, con)
    tmplist = []
    for r in rt:
        firstname = r[0]
        # print firstname
        firstname = re.sub(renameabbr, "", firstname)
        firstname = ProcessLtGt(firstname)
        firstname = ProcessSemiColonAtEnd(firstname)
        firstname = ProcessEndWordsBringToFront(firstname)
        firstname = ProcessEtc(firstname)
        firstname = ProcessAmpersand(firstname)
        firstname = firstname.replace("(Jr)", "")
        firstname = firstname.replace("(Mr.)", "")
        firstname = firstname.replace("(Mr)", "")
        firstname = firstname.replace("(Mrs.)", "")
        firstname = firstname.replace("(Mrs)", "")
        firstname = firstname.replace("(Miss)", "")
        firstname = firstname.replace("(Messrs)", "")
        firstname = firstname.replace("(Messr)", "")
        firstname = firstname.replace(",", "")
        # print firstname
        firstname = firstname.strip('?" ')
        # firstname = firstname.strip(' ')
        # print firstname
        firstnamelist = firstname.split()
        for finam in firstnamelist:
            finam = finam.strip('?" ')
            if (finam != '') and (finam not in tmplist):
                tmplist.append(finam)
    tmplist.sort()
    outfilemixname = outpre + "firstname" + outmixext
    outfilecapname = outpre + "firstname" + outcapext
    outfilelowname = outpre + "firstname" + outlowext
    outfilemixpath = os.path.join(outbasedir, outfilemixname)
    outfilecappath = os.path.join(outbasedir, outfilecapname)
    outfilelowpath = os.path.join(outbasedir, outfilelowname)
    outfilemixobj = file(outfilemixpath, "w")
    outfilecapobj = file(outfilecappath, "w")
    outfilelowobj = file(outfilelowpath, "w")
    for en in tmplist:
        print >> outfilemixobj, en
        print >> outfilecapobj, en.upper()
        print >> outfilelowobj, en.lower()
    outfilemixobj.close()
    outfilecapobj.close()
    outfilelowobj.close()
                

if __name__ == '__main__':
    con = setupMySQL("localhost", "ncse", "J0urnal", 51524, "waterloo_full_tokens")
    rowcount = 0
    
    # processWlentries()
    processTitleTable()
    # processFirstnameColumn()


    print "--== FINISHED ==--"
