<?xml version="1.0" encoding="windows-1252"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="Links_Type">
		<xs:annotation>
			<xs:documentation>Defines the links of this TOC/Page/entity.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Lnk" type="Lnk_Type" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Define a single link.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Sources" type="Sources_Type">
				<xs:annotation>
					<xs:documentation>Define the links anchors</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Lnk_Type">
		<xs:annotation>
			<xs:documentation>Hold logical part of the link: Type, Target, Level.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="LnkTitle" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Value of link title</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="LnkLabel" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Value of link title</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="TargetBox" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Box coorditates.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Target" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Value of link reference.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<!--Added by Gena-->
		</xs:sequence>
		<xs:attribute name="TYPE" type="LnkTypeAttr_Type" use="required"/>
		<xs:attribute name="LNK_ID" type="LnkIDAttr_Type" use="required"/>
		<xs:attribute name="LNK_ROLE" type="LnkRoleAttr_Type" use="optional"/>
		<xs:attribute name="LNK_LEVEL" type="xs:string" use="optional"/>
		<xs:attribute name="LNK_ZOOM_MODE" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:simpleType name="LnkRoleAttr_Type">
		<xs:annotation>
			<xs:documentation>Role of the link for the user. 
								Implemented roles that are related to Page type links only: 
									SPG- Simple page role (See page xxx); 
									CPG - Continue to page.
									IPG - Link to page in a different issue.
									TSR- Link to page that is visible from the page as teaser.
									TSR - Like TSR but to different issue.
							     Implemented roles related to URL link type:
							     		AUDIO - Link is to a audio file.
							     		VIDEO - link is to a video file.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="SPG"/>
			<xs:enumeration value="CPG"/>
			<xs:enumeration value="IPG"/>
			<xs:enumeration value="TSR"/>
			<xs:enumeration value="TSRI"/>
			<xs:enumeration value="AUDIO"/>
			<xs:enumeration value="VIDEO"/>
			<xs:enumeration value="SBX"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Sources_Type">
		<xs:annotation>
			<xs:documentation>Hold physical part of the links: Anchors boxes.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Box" type="LnkBox_Type" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Define a link anchor. Each link can have many anchors.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="LnkTypeAttr_Type">
		<xs:annotation>
			<xs:documentation>Types of links provided: "ENT" - link to entity, "PG"- link to page, "EML"- Link to e-mail, "URL" - link to external URL.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="PG"/>
			<xs:enumeration value="ENT"/>
			<xs:enumeration value="EML"/>
			<xs:enumeration value="URL"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LnkIDAttr_Type">
		<xs:annotation>
			<xs:documentation>Defines the Link ID pattern.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="LNK_([0-9]+)_([0-9]+)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="BOX_Type">
		<xs:annotation>
			<xs:documentation>Defines the BOX attribute as list of four integers.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="listOfIntegers">
			<xs:maxLength value="4"/>
			<xs:minLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="listOfIntegers">
		<xs:list itemType="xs:integer"/>
	</xs:simpleType>
	<xs:simpleType name="ID_Type">
		<xs:annotation>
			<xs:documentation>Defines the ID pattern.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="(Ar|Pc|Ad)(([0-9a-zA-Z]{5,9})|([1-9][0-9]*E[0-9]+(P[0-9]+)?))"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PageID_Type">
		<xs:annotation>
			<xs:documentation>Defines the Page ID pattern.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="Pg([0-9][0-9]*)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PageIdentifier_Type">
		<xs:annotation>
			<xs:documentation>Defines the Page ID pattern.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="PubDesc_Type">
		<xs:annotation>
			<xs:documentation>Defines the Page ID pattern.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString"/>
	</xs:simpleType>
	<xs:simpleType name="REPOSITORY_FORMAT_Type">
		<xs:annotation>
			<xs:documentation>Defines the format of Olive Repository files.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="Copyright_Type">
		<xs:annotation>
			<xs:documentation>Specifies whether entry is copyrighted or not.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="Yes"/>
			<xs:enumeration value="No"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="RenderingOpt_Type">
		<xs:annotation>
			<xs:documentation>Rendering options.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="Regular"/>
			<xs:enumeration value="Images Only"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Empty_Or_ID_Type">
		<xs:annotation>
			<xs:documentation>Allows the ID attribute to be empty.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="((Ar|Pc|Ad)(([0-9a-zA-Z]{5,9})|([1-9][0-9]*E[0-9]+(P[0-9]+)?)))?"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SNP_ID_Type">
		<xs:annotation>
			<xs:documentation>Defines the ID pattern with snippet extention.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="(Ar|Pc|Ad)(([0-9a-zA-Z]{5,9})|([1-9][0-9]*E[0-9]+(P[0-9]+)?))S?.(gif|jpg|png)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Href_Attr_Type">
		<xs:annotation>
			<xs:documentation>Defines reference to an entity or to an image. Reference starts from base href location.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="/[1-9][0-9]*(/Img)*/(Pg|Ar|Pc|Ad)(([0-9a-zA-Z]{3,9})|([1-9][0-9]*(E[0-9]+(P[0-9]+)?)?))(S)?(.jpg|.gif|.png)*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="No_Geometry_Attr_Type">
		<xs:annotation>
			<xs:documentation>Defines when entity has no physical dimentions</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="TRUE|FALSE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="BaseHref_Type">
		<xs:annotation>
			<xs:documentation>Reference to the issue in the repository. Stands as the Issue ID in the repository. The combination of BASE_HREF and ID is unique.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="[\w\i\-]+/[0-9]{4}/[0-9]{2}/[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="XmdVerAttr_Type">
		<xs:annotation>
			<xs:documentation>Version of the XMD used to create this file.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="[0-9]{1,2}.[0-9]{1,3}(.[0-9]{1,3})*"/>
			<xs:pattern value="XLC_\d+\.\d+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SourceType_Type">
		<xs:annotation>
			<xs:documentation>Enumerated type holding all valid source types.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="TIFF"/>
			<xs:enumeration value="PDF"/>
			<xs:enumeration value="XTDB"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ResFileTypes_Type">
		<xs:annotation>
			<xs:documentation>Enumerated Resource File types for Repository.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="DOC_PDF"/>
			<xs:enumeration value="PAGE_PDF"/>
			<xs:enumeration value="DOC_IMG"/>
			<xs:enumeration value="PAGE_IMG"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PageType_Type">
		<xs:annotation>
			<xs:documentation>Enumerated type holding all valid spage types.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="Single"/>
			<xs:enumeration value="Double_First"/>
			<xs:enumeration value="Double_Second"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ElementsTypes_Type">
		<xs:annotation>
			<xs:documentation>Enumerated type holding all valid elemtns types.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="HedLine_hl0"/>
			<xs:enumeration value="HedLine_hl1"/>
			<xs:enumeration value="HedLine_hl2"/>
			<xs:enumeration value="Content"/>
			<xs:enumeration value="Byline"/>
			<xs:enumeration value="Lead"/>
			<xs:enumeration value="Picture"/>
			<xs:enumeration value="Supplementary"/>
			<xs:enumeration value="Table"/>
			<xs:enumeration value="AdFrame"/>
			<xs:enumeration value="Continuation_To"/>
			<xs:enumeration value="Continuation_From"/>
			<xs:enumeration value="Lead"/>
			<xs:enumeration value="AdFrame"/>
			<xs:enumeration value="AdLogo"/>
			<xs:enumeration value="AdPicture"/>
			<xs:enumeration value="PictureText"/>
			<xs:enumeration value="Caption"/>
			<xs:enumeration value="Group"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ImgExt_Type">
		<xs:annotation>
			<xs:documentation>Enumerated type holding all valid image extentions.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="gif"/>
			<xs:enumeration value="jpg"/>
			<xs:enumeration value="png"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="EntityType_Type">
		<xs:annotation>
			<xs:documentation>Enumerated type holding all valid entity types.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="Article"/>
			<xs:enumeration value="Ad"/>
			<xs:enumeration value="Picture"/>
			<xs:enumeration value="Data"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Size_Type">
		<xs:annotation>
			<xs:documentation>Enumerated type holding all valid entity size types.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="Small"/>
			<xs:enumeration value="Medium"/>
			<xs:enumeration value="Large"/>
			<xs:enumeration value="XLarge"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="E_Attr_Type">
		<xs:annotation>
			<xs:documentation>Enumerated type holding all valid values for E attribute.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="N"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="EntityFormat_Type">
		<xs:annotation>
			<xs:documentation>Enumerated type holding all valid entity formats.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="Data"/>
			<xs:enumeration value="Table"/>
			<xs:enumeration value="LinearAd"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="LnkBox_Type">
		<xs:annotation>
			<xs:documentation>TOC link box type: has the link ID and the box only. Entity Link box type: has linkn id and primitive id.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="BOX_Type">
				<xs:attribute name="LNK_ID" type="LnkIDAttr_Type"/>
				<xs:attribute name="PRIM_ID" type="ID_Type" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<!-- Folded pages types -->
	<xs:complexType name="FoldedViews_Type" mixed="false">
		<xs:annotation>
			<xs:documentation>Hold all folded views. Used mostly for magazines. APSever 2.6 supports only one folded view.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="FoldedView" type="FoldedView_Type"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FoldedView_Type" mixed="false">
		<xs:annotation>
			<xs:documentation>Hold single folded view. Used mostly for magazines.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="FoldedViewClip" type="FoldedViewClip_Type" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="FOLDED_VIEW_ID" type="xs:integer" use="required"/>
		<xs:attribute name="FOLDED_VIEW_WIDTH" type="xs:integer" use="required"/>
		<xs:attribute name="FOLDED_VIEW_HEIGHT" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="FoldedViewClip_Type" mixed="false">
		<xs:annotation>
			<xs:documentation>Hold a single folded clip area. Used mostly for magazines.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="CLIP_SEQ_NO" type="xs:integer" use="required"/>
		<xs:attribute name="PAGE_NO" type="xs:integer" use="required"/>
		<xs:attribute name="BOX" type="BOX_Type" use="required"/>
		<xs:attribute name="CLIP_CORNER" type="ClipCornerAttr_Type" use="optional"/>
		<xs:attribute name="CLIP_CORNER_COORD" type="XYCoords_Type" use="optional"/>
	</xs:complexType>
	<xs:simpleType name="ExtPageTypeAttr_Type">
		<xs:annotation>
			<xs:documentation>Enumerated type holding all valid extensive page types. Used mostly for magazines.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="INSERTION"/>
			<xs:enumeration value="BAND"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ClipCornerAttr_Type">
		<xs:annotation>
			<xs:documentation>Enumerated type holding all valid clip corner types. Used mostly for magazines.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="TOP_LEFT"/>
			<xs:enumeration value="TOP_RIGHT"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="XYCoords_Type">
		<xs:annotation>
			<xs:documentation>Defines the X,Y attribute as list of four integers.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="listOfIntegers">
			<xs:maxLength value="2"/>
			<xs:minLength value="2"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Application_Info_Type" mixed="true">
		<xs:annotation>
			<xs:documentation>Customized application info.</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Ai_Item" type="Ai_Item_Type"/>
		</xs:sequence>
		<xs:attribute name="AI_TYPE"/>
	</xs:complexType>
	<xs:complexType name="Ai_Item_Type" mixed="true">
		<xs:annotation>
			<xs:documentation>Customized application metadata item.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="NAME" type="xs:string"/>
		<xs:attribute name="ID" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Application_Data_Type">
		<xs:annotation>
			<xs:documentation>Application customized metadata. Can contain arbitary attributes, Application_Info elements and arbitary elements from other namespaces.</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<xs:element name="Application_Info" type="Application_Info_Type"/>
				<xs:any namespace="##other" processContents="lax"/>
			</xs:choice>
		</xs:sequence>
		<xs:anyAttribute processContents="lax"/>
	</xs:complexType>
	<xs:simpleType name="Name_Type">
		<xs:annotation>
			<xs:documentation>Document Name(Title) used in EP import document to Inventory.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString"/>
	</xs:simpleType>
	<!--TOC Entries-->
	<xs:complexType name="TOC_Entry_Type" mixed="true">
		<xs:annotation>
			<xs:documentation>
								Represent logical hierarchy of a document.Inserted under
								TOC_Entries element, in TOC.xml and in first chunk Entity.xml.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<xs:element name="TOC_Entry" type="TOC_Entry_Type"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="TOC_ENTRY_ID" type="TOC_ENTRY_ID_Type" use="required">
			<xs:annotation>
				<xs:documentation>	Unique ID for each TOC_Entry node.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="TITLE" type="TITLE_Type" use="required"/>
		<xs:attribute name="ENTITY_ID_REF" type="ID_Type" use="required"/>
		<xs:attribute name="PRIM_ID_REF" type="ID_Type" use="optional"/>
		<xs:attribute name="PAGE_LABEL" type="xs:string" use="optional"/>
		<xs:attribute name="IS_IC" type="BOOL_Type" use="optional"/>
		<xs:attribute name="IS_INCOMPLETE" type="BOOL_Type" use="optional"/>
		<xs:attribute name="IS_GENERAL" type="BOOL_Type" use="optional" default="false"/>
		<xs:attribute name="PAGE_NO" type="xs:integer" use="optional"/>
	</xs:complexType>
	<xs:complexType name="TOC_Entries_Type">
		<xs:annotation>
			<xs:documentation>Main element of Logical TOC in Document</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:choice>
				<xs:element name="TOC_Entry" type="TOC_Entry_Type"/>
				<xs:any namespace="##other" processContents="strict"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<!--TOC_Entry attributes start-->
	<xs:simpleType name="TOC_ENTRY_ID_Type">
		<xs:annotation>
			<xs:documentation>Attribute TOC Entry ID, will unique per document.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:unsignedInt"/>
	</xs:simpleType>
	<xs:simpleType name="TITLE_Type">
		<xs:annotation>
			<xs:documentation>Attribute TITLE, contains entity title.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="BOOL_Type">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="true|false"/>
		</xs:restriction>
	</xs:simpleType>
	<!--Primitive TOC Entries Attribute Group-->
	<xs:attributeGroup name="Prim_TOC_Entries_Attributes_Group">
		<xs:annotation>
			<xs:documentation>Attributes related to Primitive element in Page and Entity XML files.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="TOC_ENTRY_ID" type="TOC_ENTRY_ID_Type" use="optional">
			<xs:annotation>
				<xs:documentation>Integer, unique per document</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="SEQ_NO" type="xs:unsignedInt" use="optional">
			<xs:annotation>
				<xs:documentation>Integer, presentation order of primitives in entity</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ELEMENT_SUBTYPE" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Custom string, optional</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	<!--First Chunk Attribute Group, common for TOC and Entity XML files-->
	<xs:attributeGroup name="First_Chunk_Attributes_Group">
		<xs:attribute name="DOC_UID" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					Holds document's date, significant when the issue is not periodical(Enterprise specific).
					For Entity XML: used only in first chunk (not embedded).
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="DOC_VER" type="xs:unsignedInt" use="optional">
			<xs:annotation>
				<xs:documentation>
					Holds document's version, which supposed to be incremented each time the document republished.
					For Entity XML: used only in first chunk (not embedded).
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ENTITY_SUBTYPE" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Entity subtype string.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
</xs:schema>
