CREATE TABLE categories (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  category VARCHAR(255) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE tokens (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  token VARCHAR(255) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE tokens_wlentries (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  tokenid INTEGER UNSIGNED NULL,
  wlentryid INTEGER UNSIGNED NULL,
  tokenpos INTEGER UNSIGNED NULL,
  categoryid INTEGER UNSIGNED NULL,
  PRIMARY KEY(id)
);

CREATE TABLE wlentries (
  id INTEGER NOT NULL AUTO_INCREMENT,
  wlentry TINYTEXT NULL,
  categoryid INTEGER UNSIGNED NULL,
  wlid INTEGER UNSIGNED NULL,
  PRIMARY KEY(id)
);


