package uk.ac.kcl.cch.ncse.frequency;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 * Compresses a list generated by TokenListGenerator. (Don't forget to unix sort the list first.)
 * Sending the resulting list through sort -n -r gives the final token frequency list.
 * 
 * Used by FrequencyListGenerator.
 * 
 * @author patrick
 */
public class TokenListCompressor {

	public static void compress(File inF, File  outF) throws IOException{
		BufferedReader in = new BufferedReader(new FileReader(inF));
		BufferedWriter out = new BufferedWriter(new FileWriter(outF));
		
		String lastToken = null;
		int acc = 0;
		String line = null;
		while( (line=in.readLine())!=null){
			line = line.trim();
			if(line.length()>0){
				String token = getToken(line);
				int freq = getFrequency(line);
				
				if(lastToken == null || token.equals(lastToken)){
					acc += freq;
				}
				else{
					out.write(acc+","+lastToken);
					out.newLine();
					acc = freq;
				}
				lastToken = token;
			}
		}
		in.close();
		
		out.write(lastToken+","+acc);
		out.newLine();
		out.close();
	}
	
	private static String getToken(String line){
		int split = line.lastIndexOf(',');
		if(split!=-1)
			return line.substring(0, split);
		else return line;
	}

	private static int getFrequency(String line){
		int split = line.lastIndexOf(',');
		if(split==-1)
			return 0;
		
		try{
			return Integer.parseInt(line.substring(split+1));
		}
		catch(NumberFormatException e){
			return 0;
		}
	}
	
	public static void main(String[] args) throws IOException{
		compress(new File(args[0]).getAbsoluteFile(), new File(args[1]).getAbsoluteFile());
	}
	
}
